services:
  web:
    ports:
      - "3000:3000"
    build: .
    command: npm start
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./
    #       target: /app
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json
    # depends_on:
    #   - db
#   db:
#     image: postgres:bullseye
#     restart: always
#     environment:
#       - POSTGRES_PASSWORD: db_password
#     secrets:
#       - db_password

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080

# secrets:
#   db_password:
#     file: POSTGRES_PASSWORD.txt
