export const FEATURE_FLAGS = {
  SCROLLING_CALENDAR: 1,
};

export const CHILDREN_FEATURE_FLAGS = {
  SCROLLING_CALENDAR_MONTHS_PREVIOUS: 3,
  SCROLLING_CALENDAR_MONTHS_NEXT: 4,
};

export const FORM_ACTIONS = {
  MARK_DATE: "mark-date",
  REMOVE_MARKED_HABIT: "remove-marked-habit",
};

export const SCROLLING_CALENDAR_MONTHS_PREVIOUS_DEFAULT = 4;
export const SCROLLING_CALENDAR_MONTHS_NEXT_DEFAULT = 2;
